// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Demo.Api.Models.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accessories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Collars",
                            Description = "Durable leather collar with brass buckle",
                            Name = "Leather Collar",
                            Price = 24.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Toys",
                            Description = "Bouncy ball with bell inside for interactive play",
                            Name = "Interactive Toy Ball",
                            Price = 12.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bedding",
                            Description = "Comfortable orthopedic dog bed with memory foam",
                            Name = "Soft Dog Bed",
                            Price = 49.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = "Toys",
                            Description = "Braided rope toy for tug of war",
                            Name = "Rope Toy",
                            Price = 9.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 5,
                            Category = "Grooming",
                            Description = "Slicker brush for removing loose fur and mats",
                            Name = "Grooming Brush",
                            Price = 14.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 6,
                            Category = "Feeding",
                            Description = "Stainless steel food and water bowls with rubber base",
                            Name = "Pet Food Bowl Set",
                            Price = 19.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 7,
                            Category = "Leashes",
                            Description = "16ft retractable leash with locking mechanism",
                            Name = "Retractable Leash",
                            Price = 22.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 8,
                            Category = "Housing",
                            Description = "Durable plastic crate for training and travel",
                            Name = "Pet Crate",
                            Price = 79.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 9,
                            Category = "Treats",
                            Description = "Natural rawhide chew sticks (pack of 5)",
                            Name = "Chew Stick Pack",
                            Price = 8.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 10,
                            Category = "Travel",
                            Description = "Ventilated backpack carrier for pets up to 15 lbs",
                            Name = "Pet Carrier Backpack",
                            Price = 39.99m,
                            StockQuantity = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
